name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller feedparser pystray pillow plyer pywin32

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed plugin-deals-notifier.py

    - name: Upload built executable
      uses: actions/upload-artifact@v4
      with:
        name: plugin-deals-notifier-windows
        path: dist/plugin-deals-notifier.exe
